//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotransportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basis
    {
        public byte BaseID { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
