//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotransportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductore
    {
        public string EmployeeID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int BaseID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
