//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotransportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasolinera
    {
        public byte GasolineraID { get; set; }
        public string RazonSocial { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
