//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotransportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public byte ViajeID { get; set; }
        public string SerialNumber { get; set; }
        public string EmployeeID { get; set; }
        public byte RutaID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
